
import javax.swing.JOptionPane;

 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sebastian
 */
public class Calculadora extends javax.swing.JFrame {
    
    double Num1,  Num2;
    String signo;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recibidor = new javax.swing.JLabel();
        BotonDivi = new javax.swing.JButton();
        BotonMulti = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        BotonOcho = new javax.swing.JButton();
        BotonNueve = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonSiete = new javax.swing.JButton();
        BotonCinco = new javax.swing.JButton();
        BotonSeis = new javax.swing.JButton();
        BotonCuatro = new javax.swing.JButton();
        BotonDos = new javax.swing.JButton();
        BotonTres = new javax.swing.JButton();
        BotonUno = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        setForeground(new java.awt.Color(0, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Recibidor.setBackground(new java.awt.Color(255, 255, 255));
        Recibidor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        Recibidor.setOpaque(true);
        getContentPane().add(Recibidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, 204, 30));

        BotonDivi.setBackground(new java.awt.Color(0, 0, 0));
        BotonDivi.setForeground(new java.awt.Color(255, 255, 255));
        BotonDivi.setText("/");
        BotonDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDiviActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 75, 42, 40));

        BotonMulti.setBackground(new java.awt.Color(0, 0, 0));
        BotonMulti.setForeground(new java.awt.Color(255, 255, 255));
        BotonMulti.setText("X");
        BotonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 75, 42, 40));

        BotonResta.setBackground(new java.awt.Color(0, 0, 0));
        BotonResta.setForeground(new java.awt.Color(255, 255, 255));
        BotonResta.setText("-");
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 75, 42, 40));

        Limpiar.setBackground(new java.awt.Color(0, 0, 0));
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("C");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 75, 42, 40));

        BotonOcho.setText("8");
        BotonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOchoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 121, 42, 40));

        BotonNueve.setText("9");
        BotonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNueveActionPerformed(evt);
            }
        });
        getContentPane().add(BotonNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 121, 42, 40));

        BotonSuma.setBackground(new java.awt.Color(0, 0, 0));
        BotonSuma.setForeground(new java.awt.Color(255, 255, 255));
        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 121, 42, 80));

        BotonSiete.setText("7");
        BotonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSieteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 121, 42, 40));

        BotonCinco.setText("5");
        BotonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCincoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 167, 42, 40));

        BotonSeis.setText("6");
        BotonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeisActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 167, 42, 40));

        BotonCuatro.setText("4");
        BotonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCuatroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 167, 42, 40));

        BotonDos.setText("2");
        BotonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 213, 42, 40));

        BotonTres.setText("3");
        BotonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTresActionPerformed(evt);
            }
        });
        getContentPane().add(BotonTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 213, 42, 40));

        BotonUno.setText("1");
        BotonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 213, 42, 40));

        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });
        getContentPane().add(Boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 259, 150, 40));

        BotonIgual.setBackground(new java.awt.Color(0, 0, 0));
        BotonIgual.setForeground(new java.awt.Color(255, 255, 255));
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 209, 42, 90));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setText("<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 36, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/FondoCalcula.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"0");
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnoActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"1");
    }//GEN-LAST:event_BotonUnoActionPerformed

    private void BotonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDosActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"2");
    }//GEN-LAST:event_BotonDosActionPerformed

    private void BotonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTresActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"3");
    }//GEN-LAST:event_BotonTresActionPerformed

    private void BotonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCuatroActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"4");
    }//GEN-LAST:event_BotonCuatroActionPerformed

    private void BotonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCincoActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"5");
    }//GEN-LAST:event_BotonCincoActionPerformed

    private void BotonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeisActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"6");
    }//GEN-LAST:event_BotonSeisActionPerformed

    private void BotonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSieteActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"7");
    }//GEN-LAST:event_BotonSieteActionPerformed

    private void BotonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOchoActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"8");
    }//GEN-LAST:event_BotonOchoActionPerformed

    private void BotonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNueveActionPerformed
        // TODO add your handling code here:
        Recibidor.setText(Recibidor.getText()+"9");
    }//GEN-LAST:event_BotonNueveActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        
        Recibidor.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void BotonDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDiviActionPerformed
        // TODO add your handling code here:
        Num1= Float.parseFloat(Recibidor.getText());
        signo= "/";
        Recibidor.setText("");
    }//GEN-LAST:event_BotonDiviActionPerformed

    private void BotonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiActionPerformed
        // TODO add your handling code here:
        Num1= Float.parseFloat(Recibidor.getText());
        signo= "*";
        Recibidor.setText("");
    }//GEN-LAST:event_BotonMultiActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        // TODO add your handling code here:
        Num1= Double.parseDouble(Recibidor.getText());
        signo= "-";
        Recibidor.setText("");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        // TODO add your handling code here:
        Num1= Double.parseDouble(Recibidor.getText());
        signo= "+" ;
        Recibidor.setText("");
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
        // TODO add your handling code here:
        
        Num2=Double.parseDouble(Recibidor.getText());
        switch(signo){
            case "+":
                Recibidor.setText(Double.toString(Num1+Num2));
                break;
            case "-":
                Recibidor.setText(Double.toString(Num1-Num2));
                break;  
            case "/":
                if(Num2==0 || Num1==0){
                    
                    JOptionPane.showMessageDialog(null, "No se divide entre 0");
                    Recibidor.setText(":(");
                } else{
                    Recibidor.setText(Double.toString(Num1/Num2));
                            
                    break;
                }


            case "*":
                Recibidor.setText(Double.toString(Num1*Num2));
            
                break;    
                
                
                
                
        }
        
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here

        PaginaInicial newframe= new PaginaInicial();
        newframe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton BotonCinco;
    private javax.swing.JButton BotonCuatro;
    private javax.swing.JButton BotonDivi;
    private javax.swing.JButton BotonDos;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMulti;
    private javax.swing.JButton BotonNueve;
    private javax.swing.JButton BotonOcho;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSeis;
    private javax.swing.JButton BotonSiete;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton BotonTres;
    private javax.swing.JButton BotonUno;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Recibidor;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
