/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sebastian
 */
public class Promedio extends javax.swing.JFrame {

    /**
     * Creates new form Promedio
     */
    public Promedio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtespanol1 = new javax.swing.JTextField();
        txtespanol2 = new javax.swing.JTextField();
        txtespanol3 = new javax.swing.JTextField();
        txtespanol4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtmate1 = new javax.swing.JTextField();
        txtmate2 = new javax.swing.JTextField();
        txtmate3 = new javax.swing.JTextField();
        txtmate4 = new javax.swing.JTextField();
        txtingles1 = new javax.swing.JTextField();
        txtingles2 = new javax.swing.JTextField();
        txtingles3 = new javax.swing.JTextField();
        txtingles4 = new javax.swing.JTextField();
        txtciencias1 = new javax.swing.JTextField();
        txtciencias2 = new javax.swing.JTextField();
        txtciencias3 = new javax.swing.JTextField();
        txtciencias4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtITrimestre = new javax.swing.JTextField();
        txtIITrimestre = new javax.swing.JTextField();
        txtIIITrimestre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfilosofia1 = new javax.swing.JTextField();
        txtfilosofia2 = new javax.swing.JTextField();
        txtfilosofia3 = new javax.swing.JTextField();
        txtfilosofia4 = new javax.swing.JTextField();
        txtanual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Nota = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel1.setText("Materias ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel2.setText("I Trimestre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel3.setText("II Trimestre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 51, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel4.setText("III Trimestre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 51, -1, -1));
        getContentPane().add(txtespanol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 39, -1));
        getContentPane().add(txtespanol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 39, -1));
        getContentPane().add(txtespanol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 39, -1));
        getContentPane().add(txtespanol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 46, -1));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel5.setText("Espanol");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, -1, -1));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jButton1.setText("Validar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel6.setText("Matematicas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel7.setText("Ingles");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel8.setText("Ciencias");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));
        getContentPane().add(txtmate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 39, -1));
        getContentPane().add(txtmate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 39, -1));
        getContentPane().add(txtmate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 39, -1));
        getContentPane().add(txtmate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 46, -1));
        getContentPane().add(txtingles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 39, -1));
        getContentPane().add(txtingles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 39, -1));
        getContentPane().add(txtingles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 39, -1));
        getContentPane().add(txtingles4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 46, -1));
        getContentPane().add(txtciencias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 39, -1));
        getContentPane().add(txtciencias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 39, -1));
        getContentPane().add(txtciencias3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 39, -1));
        getContentPane().add(txtciencias4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 46, -1));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel9.setText("Trimestral");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 51, -1, -1));
        getContentPane().add(txtITrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 39, -1));
        getContentPane().add(txtIITrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 39, -1));
        getContentPane().add(txtIIITrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 39, -1));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel10.setText("Filosofia");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 256, -1, -1));
        getContentPane().add(txtfilosofia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 39, -1));
        getContentPane().add(txtfilosofia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 39, -1));
        getContentPane().add(txtfilosofia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 39, -1));
        getContentPane().add(txtfilosofia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 46, -1));
        getContentPane().add(txtanual, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 46, -1));

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel11.setText("Total ITrimestre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel12.setText("Total IITrimestre");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel13.setText("Total IIITrimestre");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel14.setText("Anual");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setText("<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 36, -1));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, 630, 10));

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        jLabel16.setText("Digite sus Notas:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 17, -1, -1));

        Nota.setBackground(new java.awt.Color(255, 255, 255));
        Nota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Nota.setOpaque(true);
        getContentPane().add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 70, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/23225.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float Espanol1,Espanol2,Espanol3,SumaEspanol;
        float Mate1,Mate2,Mate3,SumaMate;
        float Ingles1,Ingles2,Ingles3,SumaIngles;
        float Ciencias1,Ciencias2,Ciencias3,SumaCiencias;
        float Filosofia1,Filosofia2,Filosofia3,SumaFilosofia;
        float PromedioEspa,PromedioMate,PromedioIngles,PromedioCiencias,PromedioFilosofia;
        float SumaITrimestre,SumaIITrimestre,SumaIIITrimestre;
        float Anual,SumaAnual,ITrimestre,IITrimestre,IIITrimestre;
        
        
        Espanol1=Float.parseFloat(txtespanol1.getText());
        Espanol2=Float.parseFloat(txtespanol2.getText());
        Espanol3=Float.parseFloat(txtespanol3.getText());
        SumaEspanol= Espanol1+Espanol2+Espanol3;
        
        PromedioEspa= SumaEspanol/3;
        
        txtespanol4.setText(""+Math.round(PromedioEspa));
        
        
        Mate1=Float.parseFloat(txtmate1.getText());
        Mate2=Float.parseFloat(txtmate2.getText());
        Mate3=Float.parseFloat(txtmate3.getText());
        SumaMate=Mate1+Mate2+Mate3;
        
        PromedioMate= SumaMate/3;
        
        txtmate4.setText(""+Math.round(PromedioMate));
        
        
        
       Ingles1=Float.parseFloat(txtingles1.getText());
       Ingles2=Float.parseFloat(txtingles2.getText());
       Ingles3=Float.parseFloat(txtingles3.getText());
       SumaIngles= Ingles1+Ingles2+Ingles3;
       
       PromedioIngles= SumaIngles/3;
       
       txtingles4.setText(""+Math.round(PromedioIngles));
      
       
       
       Ciencias1=Float.parseFloat(txtciencias1.getText());
       Ciencias2=Float.parseFloat(txtciencias2.getText());
       Ciencias3=Float.parseFloat(txtciencias3.getText());
       SumaCiencias= Ciencias1+Ciencias2+Ciencias3;
       
       PromedioCiencias= SumaCiencias/3;
       
       txtciencias4.setText(""+Math.round(PromedioCiencias));
       
       Filosofia1=Float.parseFloat(txtfilosofia1.getText());
       Filosofia2=Float.parseFloat(txtfilosofia2.getText());
       Filosofia3=Float.parseFloat(txtfilosofia3.getText());
      
       SumaFilosofia= Filosofia1+Filosofia2+Filosofia3;
       
       PromedioFilosofia= SumaFilosofia/3;
       
       txtfilosofia4.setText(""+Math.round(PromedioFilosofia));
       
       
       
       
       SumaITrimestre= (Espanol1+Mate1+Ingles1+Ciencias1+Filosofia1);
       ITrimestre= SumaITrimestre/5;
       txtITrimestre.setText(""+Math.round(ITrimestre));
       
       SumaIITrimestre= (Espanol2+Mate2+Ingles2+Ciencias2+Filosofia2);
       IITrimestre= SumaIITrimestre/5;
       txtIITrimestre.setText(""+Math.round(IITrimestre));
       
       SumaIIITrimestre= (Espanol3+Mate3+Ingles3+Ciencias3+Filosofia3);
       IIITrimestre= SumaIIITrimestre/5;
       txtIIITrimestre.setText(""+Math.round(IIITrimestre));
       
       SumaAnual= ITrimestre+IITrimestre+IIITrimestre;
       Anual= SumaAnual/3;
       txtanual.setText(""+Math.round(Anual));
        
       if (Anual<70)
           Nota.setText("Reprobado");
       
       else
           Nota.setText("Aprobado!");
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       txtfilosofia1.setText("");
       txtfilosofia2.setText("");
       txtfilosofia3.setText("");
       
       txtciencias1.setText("");
       txtciencias2.setText("");
       txtciencias3.setText("");
       
       txtingles1.setText("");
       txtingles2.setText("");
       txtingles3.setText("");
       
       txtmate1.setText("");
       txtmate2.setText("");
       txtmate3.setText("");
       
       txtespanol1.setText("");
       txtespanol2.setText("");
       txtespanol3.setText("");
       
       txtanual.setText("");
       
       txtITrimestre.setText("");
       txtIITrimestre.setText("");
       txtIIITrimestre.setText("");
       
       txtingles4.setText("");
       txtespanol4.setText("");
       txtfilosofia4.setText("");
       txtmate4.setText("");
       txtciencias4.setText("");
       
       Nota.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here

        PaginaInicial newframe= new PaginaInicial();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Nota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIIITrimestre;
    private javax.swing.JTextField txtIITrimestre;
    private javax.swing.JTextField txtITrimestre;
    private javax.swing.JTextField txtanual;
    private javax.swing.JTextField txtciencias1;
    private javax.swing.JTextField txtciencias2;
    private javax.swing.JTextField txtciencias3;
    private javax.swing.JTextField txtciencias4;
    private javax.swing.JTextField txtespanol1;
    private javax.swing.JTextField txtespanol2;
    private javax.swing.JTextField txtespanol3;
    private javax.swing.JTextField txtespanol4;
    private javax.swing.JTextField txtfilosofia1;
    private javax.swing.JTextField txtfilosofia2;
    private javax.swing.JTextField txtfilosofia3;
    private javax.swing.JTextField txtfilosofia4;
    private javax.swing.JTextField txtingles1;
    private javax.swing.JTextField txtingles2;
    private javax.swing.JTextField txtingles3;
    private javax.swing.JTextField txtingles4;
    private javax.swing.JTextField txtmate1;
    private javax.swing.JTextField txtmate2;
    private javax.swing.JTextField txtmate3;
    private javax.swing.JTextField txtmate4;
    // End of variables declaration//GEN-END:variables
}
